Function Invoke-WPFFormVariables {
Write-Host"     ▄▄▄ ▄▄▄▄▄▄▄ ▄▄▄▄▄▄ ▄▄    ▄ "
Write-Host"    █   █       █      █  █  █ █"
Write-Host"    █   █   ▄   █  ▄   █   █▄█ █"
Write-Host" ▄  █   █  █ █  █ █▄█  █       █"
Write-Host"█ █▄█   █  █▄█  █      █  ▄    █"
Write-Host"█       █       █  ▄   █ █ █   █"
Write-Host"█▄▄▄▄▄▄▄█▄▄▄▄▄▄▄█▄█ █▄▄█▄█  █▄▄█"
Write-Host"                                "
Write-Host"    ▄▄▄▄▄▄▄ ▄▄▄▄▄▄  ▄▄▄▄▄▄      "
Write-Host"   █       █      ██   ▄  █     "
Write-Host"   █▄     ▄█  ▄    █  █ █ █     "
Write-Host"     █   █ █ █ █   █   █▄▄█▄    "
Write-Host"     █   █ █ █▄█   █    ▄▄  █   "
Write-Host"     █   █ █       █   █  █ █   "
Write-Host"     █▄▄▄█ █▄▄▄▄▄▄██▄▄▄█  █▄█   "
}